# Generated by Django 5.1.2 on 2026-05-13 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BedrockCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CAPTION', 'Caption'), ('MEME', 'Meme')], max_length=10)),
                ('model_id', models.CharField(max_length=120)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bedrock_calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
