# Generated by Django 5.1.2 on 2026-05-13 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwell_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='impressions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='reactions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['-created_at', 'expires_at'], name='feed_status_created_d0091f_idx'),
        ),
        migrations.AddField(
            model_name='impression',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_logs', to='feed.status'),
        ),
        migrations.AddField(
            model_name='impression',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['status', '-created_at'], name='feed_impres_status__c54af5_idx'),
        ),
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['user', '-created_at'], name='feed_impres_user_id_f6d1d3_idx'),
        ),
    ]
