# Generated by Django 5.1.2 on 2026-05-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(max_length=16)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('crest_url', models.URLField(blank=True)),
                ('color_primary', models.CharField(default='#1e90ff', max_length=7)),
                ('color_secondary', models.CharField(default='#ffffff', max_length=7)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('FINISHED', 'Finished')], default='UPCOMING', max_length=10)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('competition', models.CharField(blank=True, max_length=80)),
                ('venue', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(default='SIMULATOR', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='matches.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='matches.team')),
            ],
            options={
                'ordering': ['-kickoff_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('KICKOFF', 'Kickoff'), ('GOAL', 'Goal'), ('OG', 'Own Goal'), ('PEN', 'Penalty'), ('YELLOW', 'Yellow'), ('RED', 'Red'), ('SUB', 'Sub'), ('HALFTIME', 'Halftime'), ('FULLTIME', 'Fulltime'), ('VAR', 'Var'), ('COMMENTARY', 'Commentary')], max_length=12)),
                ('player_name', models.CharField(blank=True, max_length=120)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.team')),
            ],
            options={
                'ordering': ['match', 'minute', 'id'],
                'indexes': [models.Index(fields=['match', 'minute'], name='matches_mat_match_i_3c5afa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'kickoff_at'], name='matches_mat_status_951bb1_idx'),
        ),
    ]
